---
title: "Lebenslauf"
author: "Joel Beck"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ["../css/multipage.css", "../css/shared.css", "resume"]
    self_contained: TRUE
knit: pagedown::chrome_print      # click Knit Button for print to pdf
---

<!-- display right side bar only on first page -->
```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Kontakt {#contact}
--------------------------------------------------------------------------------

<i class="fa fa-envelope"></i> joel.beck@stud.uni-goettingen.de

<i class="fab fa-github"></i> [github.com/joel-beck](https://github.com/joel-beck)

<i class="fab fa-linkedin"></i> [linkedin.com/joelbeck07](https://www.linkedin.com/in/joelbeck07)



Sprachen {#languages}
-------------------------------------------------------------------

  - Python (3 Jahre)

  - R (3 Jahre)

  - SQL with SQLite (1 Jahr)

  - Typescript & Javascript (6 Monate)


Workflow {#workflow}
-------------------------------------------------------------------

  - Git, GitHub & GitLab

  - CI/CD with GitHub Actions & GitLab CI

  - Docker

  - Jira & Confluence


Text {#writing}
-------------------------------------------------------------------

  - Markdown

  - RMarkdown & Quarto

  - LaTeX


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Erstellt mit [pagedown](https://github.com/rstudio/pagedown).

Source Code: <br>[github.com/joel-beck/resume](https://github.com/joel-beck/resume).

Zuletzt aktualisiert: `r Sys.Date()`.



Main
================================================================================

Joel Beck {#title}
---------------------------------------------------------------------------------


Praxiserfahrung {data-icon=chalkboard-teacher}
---------------------------------------------------------------------------------

### Praktikum: Data Scientist

eoda GmbH Kassel

N/A

01/2023 - 11/2022

- Entwicklung von MLOps Prozessen und Einführung von Unit Tests
- Entwicklung von Prognosemodellen mit `Scikit-Learn` & `Tidymodels`
- Veröffentlichung von Blogbeiträgen über das [Tidyverse](https://www.eoda.de/en/wissen/blog/10-tidyverse-functions-that-might-save-your-day/) und die Pandas Bibliothek


### Tutorenstelle Göttingen

Masterkurs Econometrics I

N/A

09/2022 - 10/2021


### Hiwi-Job Göttingen

Lehrstuhl für Statistik

N/A

04/2022 - 04/2021

- Entwicklung und Dokumentation von [Liesel](https://github.com/liesel-devs/liesel), \
ein R & Python Framework für Bayesian Regressionsmodelle


### Praktikum: Content Creator

Studybees GmbH Mannheim

N/A

06/2020 - 03/2020

- Entwicklung und Durchführung von Onlinekursen über Statistik & Ökonometrie


### Tutorenstelle Mannheim

Bachelorkurs Wahrscheinlichkeitstheorie

N/A

03/2020 - 09/2018


### Freiwilliges Soziales Jahr Saarbrücken

Trainer im Jugendsport für Kinder zwischen 1 und 16 Jahren

N/A

08/2016 - 08/2015


Bildungsweg {data-icon=graduation-cap data-concise=true}
---------------------------------------------------------------------------------

### Georg - August - Universität Göttingen

Master of Science: Angewandte Statistik

N/A <!-- do not display location marker -->

09/2023 - 09/2020

- Aktuelle Durchschnittsnote: 1,0 (Top 1%)
- Schwerpunkte Machine Learning & Deep Learning
- Masterarbeit über Recommender Systems mit NLP


### University of Oslo

ERASMUS Auslandssemester

N/A

12/2018 - 08/2018


### Universität Mannheim

Bachelor of Science: Wirtschaftsmathematik

N/A

03/2020 - 09/2016

- Abschlussnote: 1,2 (Top 10%)
- Schwerpunkte Stochastik und Optimierung


### Ludwigsgymnasium Saarbrücken

Abitur

N/A

07/2015 - 09/2007

- Abschlussnote: 1,0 (Top 1%)



Stipendium {data-icon=award}
-------------------------------------------------------------------

### Stiftung der deutschen Wirtschaft

Verliehen für akademische Leistungen und soziales Engagement

N/A

2023 - 2016



Projekte {data-icon=code}
-------------------------------------------------------------------

### readnext (Python)

Hybrid Recommender System for Computer Science Papers

N/A

2023

- NLP mit `SpaCy`, `Gensim` & `Transformers`
- Data Transformation mit `Polars`
- Clean Code, Unit Tests mit `pytest` & [Dokumentation](https://joel-beck.github.io/readnext/) mit `MkDocs`
- Source Code: [github.com/joel-beck/readnext](https://github.com/joel-beck/readnext)


### airbnb-oslo (Python)

Price Prediction Models for Airbnb Apartments in Oslo

N/A

2022

- Modellierung mit `Scikit-Learn` & `PyTorch`
- Datenanalyse mit `Pandas`
- Source Code: [github.com/joel-beck/airbnb-oslo](https://github.com/joel-beck/airbnb-oslo)


### postforecasts (R)

Post-Processing Methods for Covid-19 Forecasts

N/A

2022

- Starker Fokus auf `Tidyverse` Paketen
- Source Code: [github.com/joel-beck/post-processing-forecasts](https://github.com/joel-beck/post-processing-forecasts)


### asp21bridge (R)

Bayesian MCMC Sampler with Ridge Penalty

N/A

2021

- OOP mit S3 Klassen & Unit Tests mit `testthat`
- Source Code: [github.com/joel-beck/asp21bridge](https://github.com/joel-beck/asp21bridge)


### shrtcts (R)

RStudio Shortcuts Skripte mit dem [shrtcts](https://pkg.garrickadenbuie.com/shrtcts/) R Paket

N/A

2022

- Source Code: [github.com/joel-beck/shrtcts-mac](https://github.com/joel-beck/shrtcts-mac)


### drafts (Typescript)

Action Skripte für die [Drafts](https://getdrafts.com) App

N/A

2023

- Source Code: [github.com/joel-beck/drafts-scripts](https://github.com/joel-beck/drafts-scripts)
