---
title: "Curriculum Vitae"
author: "Joel Beck"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['custom.css', 'resume']
    self_contained: TRUE
  xaringan::moon_reader:
    self_contained: TRUE
knit: pagedown::chrome_print      # click Knit Button for print to pdf
---


Aside
================================================================================


Contact {#contact}
--------------------------------------------------------------------------------

<i class="fa fa-envelope"></i> joel.beck@stud.uni-goettingen.de

<i class="fab fa-github"></i> [joel-beck](https://github.com/joel-beck)

<i class="fab fa-linkedin"></i> https://www.linkedin.com/in/joelbeck07



Projects {#projects}
-------------------------------------------------------------------

**Python**

  - [readnext](https://github.com/joel-beck/readnext): Hybrid Recommender System for Computer Science Papers

    - NLP with `SpaCy`, `Gensim` & `Transformers`

    - Data Transformation with `Polars`

    - Clean code, unit testing with `pytest` & [documentation](https://joel-beck.github.io/readnext/) with `MkDocs`

  - [airbnb-oslo](https://github.com/joel-beck/airbnb-oslo): Price Prediction Models for Airbnb Apartments in Oslo

    - Modeling with `Scikit-Learn` & `PyTorch`

    - Data Analysis with `Pandas`

    - Term Paper written in `LaTeX`


**R**

  - [postforecasts](https://github.com/nikosbosse/post-processing-forecasts): Post-Processing Methods for Covid-19 Forecasts

    - Heavy use of `Tidyverse` packages

    - Term Paper written in `RMarkdown`

  - [asp21bridge](https://github.com/joel-beck/asp21bridge): Bayesian MCMC Sampler with Ridge Penalty

    - OOP with S3 classes

    - Unit testing with `testthat` & Documentation with `roxygen2`


Skills {#skills}
-------------------------------------------------------------------

  - Git, GitHub Actions / GitLab CI & Docker

  - Typescript & Javascript Basics

  - SQL Databases with SQLite

  - Backend Development in Python with `FastAPI` & `SQLModel`



Main
================================================================================




Joel Beck {#title}
---------------------------------------------------------------------------------




Education {data-icon=graduation-cap data-concise=true}
---------------------------------------------------------------------------------


### Georg - August - University Göttingen

Master of Science: Applied Statistics

N/A <!-- do not display location marker -->

09/2023 - 09/2020

- Current Average Grade: 1.0 (Top 1%)
- Focus on Machine Learning & Deep Learning
- Master's Thesis about Recommender Systems with NLP


### University of Oslo

ERASMUS Study Abroad

N/A

12/2018 - 08/2018


### University of Mannheim

Bachelor of Science: Business Mathematics

N/A

03/2020 - 09/2016 <!-- timeline order from bottom to top -->

- Overall Grade: 1.2 (Top 10%)
- Focus on Stochastics und Optimization

<!-- <br> vergrößert Abstand -->


<!-- ### Ludwigsgymnasium Saarbrücken

Abitur

N/A

07/2015 - 09/2007

- Overall Grade: 1.0 -->



Work Experience {data-icon=chalkboard-teacher}
---------------------------------------------------------------------------------

### Internship: Data Scientist

eoda GmbH Kassel

N/A

01/2023 - 11/2022

- Data Preprocessing, Feature Engineering, Modeling & Design/Infrastructure of Projects
- Publication of Blog Posts about the [Tidyverse](https://www.eoda.de/en/wissen/blog/10-tidyverse-functions-that-might-save-your-day/) & Pandas


### Teaching Assistant Göttingen

Master's course Econometrics I

N/A

09/2022 - 10/2021


### Research Assistant Göttingen

Chair for Statistics

N/A

04/2022 - 04/2021

- Development and Documentation of [Liesel](https://github.com/liesel-devs/liesel), \
an R & Python Framework for Bayesian Regression Models


### Internship: Content Creator

Studybees GmbH Mannheim

N/A

06/2020 - 03/2020

- Development and Teaching of Online Courses about Statistics & Econometrics



### Teaching Assistant Mannheim

Bachelor's course Probability Theory

N/A

2020 - 2018



Scholarship {data-icon=award}
-------------------------------------------------------------------

### Stiftung der deutschen Wirtschaft

N/A

N/A

2023 - 2016

  - Awarded for academic achievements and social engagement
