---
title: "Lebenslauf"
author: "Joel Beck"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['custom.css', 'resume']
    self_contained: TRUE
  xaringan::moon_reader:
    self_contained: TRUE
knit: pagedown::chrome_print      # click Knit Button for print to pdf
---


Aside
================================================================================


Kontakt {#contact}
--------------------------------------------------------------------------------

<i class="fa fa-envelope"></i> joel.beck@stud.uni-goettingen.de

<i class="fab fa-github"></i> [joel-beck](https://github.com/joel-beck)

<i class="fab fa-linkedin"></i> https://www.linkedin.com/in/joelbeck07



Projekte {#projekte}
-------------------------------------------------------------------

**Python**

  - [readnext](https://github.com/joel-beck/readnext): Hybrid Recommender System for Computer Science Papers

    - NLP mit `SpaCy`, `Gensim` & `Transformers`

    - Data Transformation mit `Polars`

    - Clean Code, Unit Tests mit `pytest` & [Dokumentation](https://joel-beck.github.io/readnext/) mit `MkDocs`

  - [airbnb-oslo](https://github.com/joel-beck/airbnb-oslo): Price Prediction Models for Airbnb Apartments in Oslo

    - Modellierung mit `Scikit-Learn` & `PyTorch`

    - Datenanalyse mit `Pandas`

    - Abschlussbericht in `LaTeX` verfasst


**R**

  - [postforecasts](https://github.com/nikosbosse/post-processing-forecasts): Post-Processing Methods for Covid-19 Forecasts

    - Heavy use of `Tidyverse` packages

    - Abschlussbericht in `RMarkdown` verfasst

  - [asp21bridge](https://github.com/joel-beck/asp21bridge): Bayesian MCMC Sampler with Ridge Penalty

    - OOP mit S3 Klassen

    - Unit Tests mit `testthat` & Dokumentation mit `roxygen2`


Skills {#skills}
-------------------------------------------------------------------

  - Git, GitHub Actions / GitLab CI & Docker

  - Typescript & Javascript Basics

  - SQL Databases mit SQLite

  - Backend Entwicklung in Python mit `FastAPI` & `SQLModel`



Main
================================================================================




Joel Beck {#title}
---------------------------------------------------------------------------------




Bildungsweg {data-icon=graduation-cap data-concise=true}
---------------------------------------------------------------------------------


### Georg - August - Universität Göttingen

Master of Science: Angewandte Statistik

N/A <!-- do not display location marker -->

seit 09/2020

- Aktuelle Durchschnittsnote: 1,0 (Top 1%)
- Schwerpunkte Machine Learning & Deep Learning
- Masterarbeit über Recommender Systems mit NLP


### University of Oslo

ERASMUS Auslandssemester

N/A

12/2018 - 08/2018


### Universität Mannheim

Bachelor of Science: Wirtschaftsmathematik

N/A

03/2020 - 09/2016

- Abschlussnote: 1,2 (Top 10%)
- Schwerpunkte Stochastik und Optimierung


<!-- ### Ludwigsgymnasium Saarbrücken

Abitur

N/A

07/2015 - 09/2007

- Abschlussnote: 1,0 -->





Praxiserfahrung {data-icon=chalkboard-teacher}
---------------------------------------------------------------------------------

### Praktikum: Data Scientist

eoda GmbH Kassel

N/A

01/2023 - 11/2022

- Datenaufbereitung, Feature Engineering, Modellierung und Design bzw. Infrastruktur von Projekten
- Veröffentlichung von Blogbeiträgen über das [Tidyverse](https://www.eoda.de/en/wissen/blog/10-tidyverse-functions-that-might-save-your-day/) und die Pandas Bibliothek


### Tutorenstelle Göttingen

Masterkurs Econometrics I

N/A

09/2022 - 10/2021


### Hiwi-Job Göttingen

Lehrstuhl für Statistik

N/A

04/2022 - 04/2021

- Entwicklung und Dokumentation von [Liesel](https://github.com/liesel-devs/liesel), \
ein R & Python Framework für Bayesian Regressionsmodelle


### Praktikum: Content Creator

Studybees GmbH Mannheim

N/A

06/2020 - 03/2020

- Entwicklung und Durchführung von Onlinekursen über Statistik & Ökonometrie



### Tutorenstelle Mannheim

Bachelorkurs Wahrscheinlichkeitstheorie

N/A

2020 - 2018



Stipendium {data-icon=award}
-------------------------------------------------------------------

### Stiftung der deutschen Wirtschaft

N/A

N/A

2023 - 2016

  - Verliehen für akademische Leistungen und soziales Engagement
